### ISSUE TITLE
Failing to build with Openfire-4.8.x

### ISSUE THREAD

**Issue by sheldonrobinson** [igniterealtime/Botz#10]
### Issue
Method `org.jivesoftware.openfire.user.UserManager.isRegisteredUser`
changed from 
```
boolean isRegisteredUser​(org.xmpp.packet.JID user)
```
to
```
boolean isRegisteredUser(org.xmpp.packet.JID user, boolean checkRemoteDomains)
```
### Error
java.lang.NoSuchMethodError: 'boolean org.jivesoftware.openfire.user.UserManager.isRegisteredUser(java.lang.String)'
        at org.igniterealtime.openfire.botz.BotzConnection.login(BotzConnection.java:358) ~[botz-1.2.1-20230310.174631-3.jar:?]
        at org.igniterealtime.openfire.botz.BotzConnection.login(BotzConnection.java:285) ~[botz-1.2.1-20230310.174631-3.jar:?]

### Affected Versions
1.2.x

### Suggested Fix
Change
`BotzConnection.java:358` from
```
if (!XMPPServer.getInstance().getUserManager().isRegisteredUser(this.jid.getNode())) {
```
to 
```
if (!XMPPServer.getInstance().getUserManager().isRegisteredUser(this.jid.getNode()), false) {
```

**Comment by guusdk** [comment]
That seems a sensible solution. Can you prepare a pull request please?
